# Camuda Process Engine UI
camunda.bpm:
  admin-user:
    id: admin
    password: admin
    firstName: Admin
  filter:
    create: All tasks
  history-level: full
  database:
    type: h2

spring:
  h2.console:
    enabled: true
    path: /h2-console
  datasource:
#    url: jdbc:h2:~/camunda;DB_CLOSE_ON_EXIT=false #Persintance
    url: jdbc:h2:mem:camunda # In Memory
#    url: jdbc:postgresql://[::1]:5740/database
#    driver-class-name: org.postgresql.Driver
#    username: camunda
#    password: camunda
# Message Broker
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange:
      rpc: invoice.rpc
      pub: invoice.pub

logging:
  level:
    org.camunda.bpm.example: DEBUG
    org.camunda.bpm: INFO #DEBUG
    org.springframework: INFO